name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
    paths:
      - 'src/**.jl'
      - 'docs/**'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'
      - name: Add registry
        run: julia --project=@. -e 'using Pkg; Pkg.Registry.add("General"); Pkg.Registry.add(RegistrySpec(url = "https://github.com/astro-group-bristol/AstroRegistry"))'
        working-directory: ./docs
      - uses: actions/cache@v3
        with:
          path: ~/.julia
          key: docs-juliadepot
      - name: Install dependencies
        run: julia --project=@. -e 'using Pkg; Pkg.instantiate()'
        working-directory: ./docs
        env:
          PYTHON: ""
      - name: Build and deploy
        run: julia --project=@. make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./docs