name: Unit Tests

on: 
  push:
    paths:
      - 'src/**.jl'
      - 'test/**.jl'
      - 'Manifest.toml'
      - 'Project.toml'
      - '.github/tests.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        julia-version: ['1.10']
        os: [ubuntu-latest]
        experimental: [false]
        include:
         - julia-version: '1.11'
           os: ubuntu-latest
           experimental: true
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
      - name: Add registry
        run: julia --project=@. setup_registry.jl
        working-directory: ./test
      - uses: actions/cache@v4
        with:
          path: ~/.julia
          key: ${{ matrix.os }}-${{ matrix.julia-version }}-juliadepot
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: ""
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v4.0.1
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
