name: Unit Tests

on: 
  push:
    paths:
      - 'src/**.jl'
      - 'test/**.jl'
      - 'Manifest.toml'
      - 'Project.toml'
      - '.github/tests.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        julia-version: ['1.9']
        os: [ubuntu-latest]
        experimental: [false]
        include:
          - julia-version: '1.10'
            os: ubuntu-latest
            experimental: true
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Add registry
        run: julia --project=@. setup_registry.jl
        working-directory: ./test
      - uses: actions/cache@v3
        with:
          path: ~/.julia
          key: ${{ matrix.os }}-${{ matrix.julia-version }}-juliadepot
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: ""
      - uses: julia-actions/julia-runtest@v1
