name: Unit Tests

on: 
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: true
      matrix:
        julia-version: ['1.9.2']
        os: [ubuntu-latest, macOS-latest]
        experimental: [false]
        include:
          - julia-version: nightly
            os: [ubuntu-latest]
            experimental: true
          - julia-version: '1.9.2'
            os: [windows-latest]
            experimental: true
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Add registry
        run: julia --project=@. -e 'using Pkg; Pkg.Registry.add("General"); Pkg.Registry.add(RegistrySpec(url = "https://github.com/astro-group-bristol/AstroRegistry"))'
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: ""
      - uses: julia-actions/julia-runtest@v1